// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8oCBgU-mCuVUtyMSoIVxUMKxAra-zsqA',
    appId: '1:37486478707:android:90a4c0fd721f083c36b106',
    messagingSenderId: '37486478707',
    projectId: 'tt-elearning-f84d2',
    storageBucket: 'tt-elearning-f84d2.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPUfAWg2kmUnb1Kmu5lxS_zK8TcMHK4qA',
    appId: '1:37486478707:web:990c88f53eb9fc5236b106',
    messagingSenderId: '37486478707',
    projectId: 'tt-elearning-f84d2',
    authDomain: 'tt-elearning-f84d2.firebaseapp.com',
    storageBucket: 'tt-elearning-f84d2.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuhani8P2M-05Ec5YS9PMAbqaOO6eweJE',
    appId: '1:37486478707:ios:baf7355665a8845736b106',
    messagingSenderId: '37486478707',
    projectId: 'tt-elearning-f84d2',
    storageBucket: 'tt-elearning-f84d2.firebasestorage.app',
    iosBundleId: 'com.example.elearningApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuhani8P2M-05Ec5YS9PMAbqaOO6eweJE',
    appId: '1:37486478707:ios:baf7355665a8845736b106',
    messagingSenderId: '37486478707',
    projectId: 'tt-elearning-f84d2',
    storageBucket: 'tt-elearning-f84d2.firebasestorage.app',
    iosBundleId: 'com.example.elearningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPUfAWg2kmUnb1Kmu5lxS_zK8TcMHK4qA',
    appId: '1:37486478707:web:1515abe362e191dc36b106',
    messagingSenderId: '37486478707',
    projectId: 'tt-elearning-f84d2',
    authDomain: 'tt-elearning-f84d2.firebaseapp.com',
    storageBucket: 'tt-elearning-f84d2.firebasestorage.app',
  );

}